// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIotMiLm9oRd4HxrOHIE1frtFGKvBnpZU',
    appId: '1:508463448026:web:303024deb5bee17e080ae3',
    messagingSenderId: '508463448026',
    projectId: 'cmsc23-jbcortes',
    authDomain: 'cmsc23-jbcortes.firebaseapp.com',
    storageBucket: 'cmsc23-jbcortes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtuDjoMgkd_a16qPRN96RLFr-iLqL2kE4',
    appId: '1:508463448026:android:351019242ceb9ab7080ae3',
    messagingSenderId: '508463448026',
    projectId: 'cmsc23-jbcortes',
    storageBucket: 'cmsc23-jbcortes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtVObaOK8amAZsFq_dc6Xmqpa1BNDdwks',
    appId: '1:508463448026:ios:4085fb908ed3467f080ae3',
    messagingSenderId: '508463448026',
    projectId: 'cmsc23-jbcortes',
    storageBucket: 'cmsc23-jbcortes.appspot.com',
    iosClientId:
        '508463448026-gna5i94fm68a1pjujc76ji0bjpj55ubi.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtVObaOK8amAZsFq_dc6Xmqpa1BNDdwks',
    appId: '1:508463448026:ios:4085fb908ed3467f080ae3',
    messagingSenderId: '508463448026',
    projectId: 'cmsc23-jbcortes',
    storageBucket: 'cmsc23-jbcortes.appspot.com',
    iosClientId:
        '508463448026-gna5i94fm68a1pjujc76ji0bjpj55ubi.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
